export enum HeroicFeatCardType{
    BLACKSMITHS_HAMMER = "BLACKSMITHS_HAMMER",
    THE_ELDER = "THE_ELDER",
    BLACKSMITHS_CHEST = "BLACKSMITHS_CHEST",
    WILD_SPIRITS = "WILD_SPIRITS",
    SILVER_HIND = "SILVER_HIND",
    GUARDIANS_OWL = "GUARDIANS_OWL",
    SATYRS = "SATYRS",
    MINOTAUR = "MINOTAUR",
    FERRYMAN = "FERRYMAN",
    GORGON = "GORGON",
    HELMET_OF_INVISIBILITY = "HELMET_OF_INVISIBILITY",
    MIRROR_OF_THE_ABYSS = "MIRROR_OF_THE_ABYSS",
    CANCER = "CANCER",
    SPHINX = "SPHINX",
    HYDRA = "HYDRA"
}


export enum CostType {
    MOON,
    SUN,
    BOTH
}